// Start member-chat-preview.mjs first; all accounts/messages are synthetic and loopback-only.
// PLAYWRIGHT_PATH may point to an existing installed Playwright package; no dependency changes.
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const errors = []; const pages = [];
const base = process.env.CHAT_PREVIEW_URL || 'http://127.0.0.1:8804';
async function page(as) {
  const p = await context.newPage(); pages.push(p); p.on('pageerror', error => errors.push(error.message));
  await p.clock.install(); await p.goto(base + '/?as=' + as); return p;
}
const wait = (p, fn) => p.waitForFunction(fn, null, { timeout: 10000 });
async function send(p, body) {
  await p.locator('#mc-body').fill(body); await p.locator('.mc-compose button').click();
  await wait(p, () => document.querySelector('#mc-body').value === '');
}
try {
  const a = await page('a');
  let releaseMe;
  await a.route('**/v1/member-chat/me', async route => { await new Promise(resolve => { releaseMe = resolve; }); await route.continue(); });
  await a.locator('#open').click(); await a.locator('nav [data-action="members"]').click();
  assert.equal(await a.locator('.mc-settings').isVisible(), false, 'settings stay hidden even while identity is loading');
  assert.equal(await a.locator('.mc-hint').isVisible(), false);
  await new Promise(resolve => setTimeout(resolve, 50)); releaseMe();
  await a.locator('[data-handle="card-b"]').waitFor(); await a.unroute('**/v1/member-chat/me');
  assert.equal(await a.locator('.mc-contact').count(), 2);
  assert.equal(await a.locator('[data-handle="card-b"] .mc-match').textContent(), '82%');
  assert.equal(await a.locator('#mc-industry option').count(), 17);
  const filterBox = await a.locator('#mc-industry').boundingBox(), queryBox = await a.locator('#mc-query').boundingBox();
  assert.ok(filterBox.y >= queryBox.y + queryBox.height && filterBox.height >= 44 && filterBox.x + filterBox.width <= 390);
  await a.locator('#mc-industry').selectOption('餐飲食品');
  await wait(a, () => document.querySelectorAll('.mc-contact').length === 1 && document.querySelector('.mc-status').textContent === '');
  assert.equal(await a.locator('[data-handle="card-b"]').count(), 1);
  await a.locator('#mc-query').fill('DEMOCHEN'); await a.locator('#mc-industry').selectOption('科技資訊');
  await a.locator('.mc-empty').waitFor();
  await a.locator('#mc-industry').selectOption('零售電商'); await a.locator('[data-handle="card-b"]').waitFor();
  assert.equal(await a.locator('#mc-query').inputValue(), 'DEMOCHEN', 'changing industry preserves text search');
  await a.locator('#mc-query').fill('');
  let releaseIndustry, industryReady;
  const delayedIndustry = new Promise(resolve => { industryReady = resolve; });
  await a.route('**/v1/member-chat/members?*', async route => {
    if (new URL(route.request().url()).searchParams.get('industry') === '科技資訊') {
      const response = await route.fetch(); industryReady();
      await new Promise(resolve => { releaseIndustry = resolve; }); await route.fulfill({ response });
    } else await route.continue();
  });
  await a.locator('#mc-industry').selectOption('科技資訊'); await delayedIndustry;
  await a.locator('#mc-industry').selectOption('餐飲食品'); await a.locator('[data-handle="card-b"]').waitFor();
  const staleResponse = a.waitForResponse(response => response.url().includes('industry=') && new URL(response.url()).searchParams.get('industry') === '科技資訊');
  releaseIndustry(); await (await staleResponse).finished(); await a.unroute('**/v1/member-chat/members?*');
  await a.locator('[data-action="refresh"]').click(); await wait(a, () => document.querySelector('.mc-status').textContent === '');
  assert.equal(await a.locator('[data-handle="card-c"]').count(), 0, 'stale industry request cannot replace selected results');
  const industryScreenshot = join(tmpdir(), 'member-chat-industry-mobile.png'); await a.screenshot({ path: industryScreenshot });
  await a.locator('#mc-industry').selectOption('');
  await wait(a, () => document.querySelectorAll('.mc-contact').length === 2);
  await a.locator('#mc-query').fill('DEMOCHEN'); await a.locator('.mc-search button').click();
  await wait(a, () => document.querySelectorAll('.mc-contact').length === 1 && document.querySelector('.mc-status').textContent === '');
  assert.equal(await a.locator('[data-handle="card-b"]').count(), 1);
  await a.locator('#mc-query').fill('找不到的會員'); await a.locator('.mc-search button').click();
  await a.locator('.mc-empty').waitFor(); assert.match(await a.locator('.mc-empty').textContent(), /已建立本人名片/);
  await a.locator('#mc-query').fill('dEmO cHeN'); await a.locator('.mc-search button').click(); await a.locator('[data-handle="card-b"]').waitFor();
  await a.locator('[data-handle="card-b"]').click(); await wait(a, () => document.querySelector('.mc-peer strong').textContent.includes('小陳'));
  await send(a, '您好！想了解咖啡禮盒合作 ☕');
  const b = await page('b'); await b.locator('#open').click();
  assert.equal(await b.locator('.mc-settings').isVisible(), true, 'My Chats retains all preferences');
  assert.equal(await b.locator('.mc-hint').isVisible(), true);
  await b.locator('[data-notifications]').check();
  await wait(b, () => document.querySelector('.mc-status').textContent.includes('已開啟 LINE通知'));
  await b.locator('[data-action="edit-line-contact"]').click();
  await b.locator('#mc-line-contact').fill('javascript:alert(1)'); await b.locator('.mc-line-form [type=submit]').click();
  await b.locator('.mc-line-form [role=status]', { hasText: '請填寫' }).waitFor();
  let failContactSave = true;
  await b.route('**/v1/member-chat/line-contact', route => route.request().method() === 'POST' && failContactSave ? route.fulfill({ status: 503, json: { success: false, error: '合成儲存失敗' } }) : route.continue());
  await b.locator('#mc-line-contact').fill('demo_chen'); await b.locator('.mc-line-form [type=submit]').click();
  await b.locator('.mc-line-form [role=status]', { hasText: '合成儲存失敗' }).waitFor();
  assert.equal(await b.locator('#mc-line-contact').inputValue(), 'demo_chen');
  failContactSave = false; await b.locator('.mc-line-form [type=submit]').click();
  await b.locator('.mc-popup').waitFor({ state: 'detached' }); await b.unroute('**/v1/member-chat/line-contact');
  assert.equal(await b.locator('[data-notifications]').isChecked(), true);
  await b.locator('[data-action="edit-line-contact"]').click();
  await wait(b, () => document.querySelector('#mc-line-contact')?.value === 'https://line.me/ti/p/~demo_chen');
  await b.screenshot({ path: join(tmpdir(), 'member-chat-line-contact-popup.png') });
  await b.keyboard.press('Escape'); assert.equal(await b.locator('dialog').count(), 1);
  await b.locator('.mc-contact').first().click();
  await wait(b, () => document.querySelector('.mc-rows').textContent.includes('咖啡禮盒'));
  await a.locator('[data-action="line-contact"]').click();
  await a.locator('.mc-popup a[href="https://line.me/ti/p/~demo_chen"]').waitFor();
  assert.equal(await a.locator('.mc-popup').evaluate(node => node.scrollWidth <= innerWidth), true);
  await a.locator('.mc-popup header button').click();
  await b.locator('[data-action="line-contact"]').click();
  await b.locator('.mc-popup-body', { hasText: '對方尚未新增' }).waitFor(); await b.locator('.mc-popup header button').click();
  await a.locator('[data-action="card"]').click();
  await a.locator('.mc-popup-body', { hasText: '對方尚未公開名片' }).waitFor();
  await a.locator('.mc-popup header button').click();
  await b.locator('[data-action="card"]').click();
  await b.locator('.mc-card-links a[href="mailto:demo@example.com"]').waitFor();
  assert.equal(await b.locator('.mc-popup').evaluate(node => node.scrollWidth <= innerWidth), true);
  await b.screenshot({ path: join(tmpdir(), 'member-chat-card-popup.png') });
  await b.locator('.mc-popup header button').click();
  await a.locator('[data-action="attach"]').click();
  await a.locator('.mc-coupon-option').click();
  assert.match(await a.locator('[data-selected-coupon]').textContent(), /合成咖啡/);
  assert.equal(await a.locator('[data-action="coupon"]').count(), 0, 'choosing alone does not send');
  await a.locator('.mc-compose button').click();
  await a.locator('[data-action="coupon"]').waitFor();
  await b.locator('[data-action="refresh"]').click(); await b.locator('[data-action="coupon"]').waitFor();
  await b.locator('[data-action="coupon"]').click(); await b.locator('[data-redeem]').waitFor();
  assert.match(await b.locator('.mc-popup-body').textContent(), /2099/);
  await b.screenshot({ path: join(tmpdir(), 'member-chat-coupon-popup.png') });
  await b.locator('[data-redeem]').click(); await b.locator('[data-confirm-redeem]').click();
  await b.locator('.mc-popup-body [role=status]', { hasText: '核銷成功' }).waitFor();
  await b.locator('.mc-popup header button').click(); await b.locator('[data-action="coupon"]').click();
  await b.locator('.mc-popup-body [role=status]', { hasText: '已核銷' }).waitFor();
  assert.equal(await b.locator('[data-redeem]').count(), 0);
  await b.locator('.mc-popup header button').click();
  await send(b, '您好！歡迎交流，我們可以一起討論。');
  await a.locator('[data-action="refresh"]').click(); await wait(a, () => document.querySelector('.mc-rows').textContent.includes('一起討論'));
  await send(b, '這是對方先送出、稍後才同步的訊息'); await send(a, '本機先顯示的回覆');
  await a.locator('[data-action="refresh"]').click(); await wait(a, () => document.querySelector('.mc-rows').textContent.includes('稍後才同步'));
  const sequences = await a.locator('.mc-message').evaluateAll(nodes => nodes.map(node => Number(node.dataset.seq)));
  assert.deepEqual(sequences, [...sequences].sort((x, y) => x - y)); assert.equal(new Set(sequences).size, sequences.length);
  const sizes = await a.evaluate(() => { const modal = document.querySelector('dialog'), close = document.querySelector('[data-action="close"]'), send = document.querySelector('.mc-compose button'); return { width: modal.scrollWidth, viewport: innerWidth, close: close.getBoundingClientRect().top, send: send.getBoundingClientRect().bottom, height: innerHeight }; });
  assert.ok(sizes.width <= sizes.viewport && sizes.close >= 0 && sizes.send <= sizes.height);
  const screenshot = join(tmpdir(), 'member-chat-mobile.png'); await a.screenshot({ path: screenshot });
  let dropped = false;
  await a.route('**/v1/member-chat/threads/*/messages', async route => {
    if (route.request().method() === 'POST' && !dropped) { dropped = true; await route.fetch(); await route.abort('failed'); }
    else await route.continue();
  });
  await a.locator('#mc-body').fill('網路回應遺失後重試'); await a.locator('.mc-compose button').click();
  await wait(a, () => document.querySelector('.mc-compose button').textContent === '重試傳送');
  await a.unroute('**/v1/member-chat/threads/*/messages'); await a.locator('.mc-compose button').click();
  await wait(a, () => document.querySelector('#mc-body').value === ''); await a.locator('[data-action="refresh"]').click();
  assert.equal(await a.locator('.mc-message p', { hasText: '網路回應遺失後重試' }).count(), 1);
  await b.locator('[data-action="block"]').click(); await wait(b, () => document.querySelector('[data-action="block"]').textContent === '解除封鎖');
  await a.locator('[data-action="refresh"]').click(); await wait(a, () => document.querySelector('.mc-compose button').disabled);
  await b.locator('[data-action="block"]').click(); await wait(b, () => document.querySelector('[data-action="block"]').textContent === '封鎖');
  await a.locator('[data-action="refresh"]').click(); await wait(a, () => !document.querySelector('[data-action="card"]').disabled);
  const c = await page('c'); await c.locator('#open').click(); await c.locator('.mc-empty').waitFor(); assert.equal(await c.locator('.mc-contact').count(), 0);
  let requests = 0; a.on('request', req => { if (req.url().includes('/v1/member-chat/')) requests++; });
  await a.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); });
  const start = requests; await a.clock.fastForward(45000); assert.equal(requests, start, 'background makes no polling calls');
  await a.locator('[data-action="card"]').click(); await a.locator('.mc-popup').waitFor();
  await a.evaluate(() => { window.currentUserProfile.userId = 'changed-account'; Object.defineProperty(document, 'hidden', { configurable: true, get: () => false }); document.dispatchEvent(new Event('visibilitychange')); });
  assert.equal(await a.locator('dialog').count(), 0, 'account change removes private UI');
  const stopped = requests; await a.clock.fastForward(45000); assert.equal(requests, stopped, 'closed view makes no polling calls');
  await b.setViewportSize({ width: 1440, height: 900 });
  assert.ok(await b.locator('dialog').evaluate(node => node.getBoundingClientRect().width <= 620));
  await b.locator('[data-action="close"]').click(); await b.close();
  const sender = await page('a'); await sender.locator('#open').click();
  const roomId = await sender.locator('.mc-contact').first().getAttribute('data-room');
  await sender.locator('.mc-contact').first().click(); await send(sender, '關閉頁面後仍應收到通知（合成測試）');
  await context.request.post(base + '/fixture-drain');
  const fixture = await (await context.request.get(base + '/fixture-status')).json();
  assert.equal(fixture.pushes.length, 1); assert.doesNotMatch(JSON.stringify(fixture.pushes), /合成測試|咖啡禮盒/);
  const reopened = await page('b&memberChat=' + roomId);
  await wait(reopened, () => document.querySelector('.mc-rows')?.textContent.includes('關閉頁面後仍應收到通知'));
  await reopened.locator('[data-action="back"]').click();
  assert.equal(await reopened.locator('[data-notifications]').isChecked(), true, 'notification setting persists');
  await reopened.locator('[data-notifications]').uncheck();
  await wait(reopened, () => document.querySelector('.mc-status').textContent.includes('已關閉 LINE通知'));
  await reopened.locator('[data-action="edit-line-contact"]').click();
  await wait(reopened, () => document.querySelector('#mc-line-contact')?.value === 'https://line.me/ti/p/~demo_chen');
  await reopened.locator('#mc-line-contact').fill(''); await reopened.locator('.mc-line-form [type=submit]').click();
  await reopened.locator('.mc-popup').waitFor({ state: 'detached' });
  await sender.locator('[data-action="line-contact"]').click();
  await sender.locator('.mc-popup-body', { hasText: '對方尚未新增' }).waitFor(); await sender.locator('.mc-popup header button').click();
  await send(sender, '關閉通知後不推播'); await context.request.post(base + '/fixture-drain');
  assert.equal((await (await context.request.get(base + '/fixture-status')).json()).pushes.length, 1);
  await reopened.setViewportSize({ width: 1440, height: 900 });
  await reopened.locator('nav [data-action="members"]').click(); await reopened.locator('#mc-industry').selectOption('科技資訊');
  await reopened.locator('[data-handle="card-c"]').waitFor();
  assert.equal(await reopened.locator('.mc-settings').isVisible(), false);
  assert.equal(await reopened.locator('.mc-hint').isVisible(), false);
  assert.equal(await reopened.locator('.mc-contact').count(), 1);
  assert.ok(await reopened.locator('dialog').evaluate(node => node.scrollWidth <= 620));
  assert.deepEqual(errors, []);
  console.log('PASS LINE contact: mobile POP, invalid input, save failure/retry, persisted/cleared contact, peer-only link, unset state, independent opt-in and closed-page push');
  console.log('PASS extras: reused 82% score, attachment selection/send, peer card POP + private denial, coupon popup + explicit single-use redemption, popup cleanup on account change');
  console.log(JSON.stringify({ result: 'PASS', checks: ['industry control below text search', 'primary/secondary industry and text intersection', 'stale filter response ignored', 'clear industry restores all', 'desktop industry filter', 'unpublished own card English-name search without phone', 'empty search feedback', 'two-party replies', 'third-party isolation', 'receive cursor and chronological order', 'lost-response retry', 'block/unblock', 'background/close polling stop', 'account change cleanup', 'mobile/desktop layout', 'explicit notification opt-in', 'synthetic push with recipient page closed', 'notification deep link opens authorized thread', 'persisted opt-out stops push'], screenshot, industryScreenshot }));
} finally { await browser.close(); }
