// Explicit allowlist, loopback-only. No production API or point calls.
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=new URL('../',import.meta.url);
export function createGomokuPreview(){
  const assets=new Set(['css/gomoku.css','assets/gomoku/cat-friends-v1.png',...['gomoku-controller','gomoku-engine','gomoku-ai-worker','gomoku-audio'].map(n=>`js/modules/${n}.mjs`)]);
  const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>喵喵五子棋｜點數通・本機試玩</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/css/gomoku.css"><style>body{margin:0;background:#f8f5ec;background-image:radial-gradient(#c5b89c20 .7px,transparent .7px);background-size:8px 8px}#launcher{text-align:center;font-family:system-ui;padding:100px 24px;color:#497c67}#launcher button{font:inherit;background:#497c67;border:0;border-radius:12px;color:white;padding:14px 28px}#launcher[hidden]{display:none}</style></head><body><main id="game"></main><section id="launcher" hidden><h1>謝謝你陪小貓下棋 ♡</h1><p>已離開試玩，遊戲與音樂都已停止。</p><button id="open">再玩一局</button></section><script type="module">import {createGomoku} from '/js/modules/gomoku-controller.mjs';const host=document.querySelector('#game'),launcher=document.querySelector('#launcher');function mount(){launcher.hidden=true;window.gomokuPreview=createGomoku(host,{onExit:()=>{launcher.hidden=false;document.querySelector('#open').focus();}});}document.querySelector('#open').addEventListener('click',mount);mount();</script></body></html>`;
  const server=createServer((req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self' blob:; connect-src 'none'; worker-src 'self'");try{if(req.method!=='GET'){res.writeHead(405);res.end();return;}const path=new URL(req.url,'http://localhost').pathname.slice(1);if(!path){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);}else if(assets.has(path)){res.setHeader('Content-Type',path.endsWith('.css')?'text/css; charset=utf-8':path.endsWith('.png')?'image/png':'text/javascript; charset=utf-8');res.end(readFileSync(new URL(path,root)));}else{res.writeHead(404);res.end('Not found');}}catch{res.writeHead(500);res.end('Preview unavailable');}});
  return {server,close:()=>new Promise(r=>server.close(r))};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const port=Number(process.env.GOMOKU_PREVIEW_PORT||8794);createGomokuPreview().server.listen(port,'127.0.0.1',()=>console.log(`Gomoku preview http://127.0.0.1:${port}/ — local practice, no points`));}
